export const VIRIFY_EMAIL =
	"Recuerde verificar el registro dando clic en el enlace enviado a su correo 🍺";
export const NO_TOKEN = "Requiere un token";
export const UNAUTHORIZED = "No autorizado";
export const SUCCESSFUL_REGISTRATION = "Registro exitoso";
export const ALREADY_EXISTS = "Ya existe este recurso";
export const SUCCESS = "👍";
export const ERR = "err";
export const NOT_FOUND = "Recurso no encontrado";
export const DESTROY = "Recurso eliminado correctamente";
export const REQUIRE_MASTER = "Requiere rol Master";
export const REQUIRE_ADMIN = "Requiere rol Admin";
export const EMAIL_UNAVAILABLE = "Correo electrónico no disponible";
export const REQUIRE_EMAIL_AND_PASS = "Requiere usuario y contraseña";
export const UNREGISTERED_USER = "Usuario no registrado";
export const USER_NOT_VERIFIED = "Usuario no verificado";
export const USER_NOT_ACTIVE = "Usuario no activo";
export const BAD_CREDENTIALS = "Credenciales incorrectas";
export const SUCCESS_CREATED_PRODUCT = "Producto creado con éxito 👍";
